# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\";\n\x0c\x46ileResponse\x12\x0f\n\x05\x63hunk\x18\x01 \x01(\x0cH\x00\x12\x13\n\tfile_size\x18\x02 \x01(\x05H\x00\x42\x05\n\x03xxx29\n\x08\x44ownload\x12-\n\x0c\x44ownloadFile\x12\x0c.FileRequest\x1a\r.FileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEREQUEST']._serialized_start=14
  _globals['_FILEREQUEST']._serialized_end=45
  _globals['_FILERESPONSE']._serialized_start=47
  _globals['_FILERESPONSE']._serialized_end=106
  _globals['_DOWNLOAD']._serialized_start=108
  _globals['_DOWNLOAD']._serialized_end=165
# @@protoc_insertion_point(module_scope)
